# this workflow is for mirrorz-help forks
name: Rebase Upstream
on:
  repository_dispatch: # on upstream push, it will notify 'some' forks (maintained in forks.yml)
    types: [mirrorz-org-push]
  workflow_dispatch: # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository != 'mirrorz-org/mirrorz-help'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 32 # greater than the number of commits the fork made
    - uses: imba-tjd/rebase-upstream-action@0.5
      with:
        upstream: mirrorz-org/mirrorz-help
        branch:   master
